services:
  backend:
    stop_grace_period: 0s
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
      - ./backend/countries.sqlite:/app/countries.sqlite

  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_DEV_SERVER_HOST=0.0.0.0
    command: ["npm", "run", "dev", "--", "--host"]
    stop_grace_period: 0s
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./client/src:/app/src
